version: "3"
services:
  pipeline:
    image: daisyorg/pipeline2
    environment:
      PIPELINE2_AUTH: "false"
      PIPELINE2_LOCAL: "false"
      PIPELINE2_HOST: "pipeline"
  webui:
    image: daisyorg/webui
    environment:
      DAISY_PIPELINE2_URL: http://pipeline:8181/ws
    ports:
      - "9000:9000"
    volumes:
      - "webui-data:/opt/pipeline2-webui/data"
    depends_on:
      - pipeline

volumes:
  webui-data:
